
pipeline_name: OCR

text_type: general

use_doc_preprocessor: False
use_textline_orientation: False

SubModules:  
  TextRecognition:
    module_name: text_recognition
    model_name: PP-OCRv5_server_rec 
    model_dir: null
    batch_size: 1
    score_thresh: 0.0